png("../docs/TaskLineGraph.png", width=700, height=700)
xrange=c(1, 10000)
yrange=c(1,3300)
plot(xrange, yrange, type="n", xlab="Update", ylab="Number of Organisms Performing Task")

red= rgb(1,0,0,0.3)
orange= rgb(1,0.4,0,0.3)
green= rgb(0,1,0,0.3)
yellow= rgb(1,1,0,0.3)
blue= rgb(0,0,1,0.3)
purple= rgb(1,0,1,0.3)
colors<-c(red,orange,green,yellow,blue,purple)
names<-c("AND (Lane)", "EQUALS (Lane)", "AND (Nedu)", "EQUALS (Nedu)", "AND (Sarah", "EQUALS (Sarah)")

for (i in 1:20){
    data <- read.table(paste("../saved_data/lane/experimental_data_", i, "/tasks.dat", sep=""))
    attach(data)
    lines(V1, V4, lwd=2.0, col=red)
    lines(V1, V10, col=orange)
    detach(data)
    data <- read.table(paste("../saved_data/nedu/experimental_data_", i, "/tasks.dat", sep=""))
    attach(data)
    lines(V1, V4, col=green)
    lines(V1, V10, col=yellow)
    detach(data)
    data <- read.table(paste("../saved_data/sarah/experimental_data_", i, "/tasks.dat", sep=""))
    attach(data)
    lines(V1, V4, col=blue)
    lines(V1, V10, col=purple)
    detach(data)
}

legend(6000, 1500, names, col=colors, lwd=4, cex=0.8, title="Legend: Task (Group Member)")
title("Count of Tasks Exclusive to Invasive Genotype Performed\nOver 20 Trials for Each Group Member")
dev.off()
